%%Author: Andrew Fletcher
%%Email: afletche@ucsd.edu
%%This program is for performing CLPT analysis

function [MS, failed_plies, failed_side, failed_z, fail_mode, fail_tcs] ...
    = CLPT(mat_props, thetas, rad_or_deg, thicknesses, mech_loading,...
    delta_T, cte_vec, fail_crit, mat_strengths_t, mat_strengths_c, SF, ...
    print_output)

[stresses_bot, stresses_top, z_all] = ...
get_local_lamina_stresses_planar_ortho(mat_props, thetas, ...
rad_or_deg, thicknesses, mech_loading, delta_T, cte_vec);

[MS, failed_plies, failed_side, failed_z, fail_mode, fail_tcs] ...
= report_ply_margins(stresses_bot, stresses_top, z_all, ...
fail_crit, mat_strengths_t, mat_strengths_c, SF, print_output);