density = 1.225;
viscosity = 1.789*10^-5;
velocity = 20;
sWing = 0.80658;
saWing = 2*sWing;
chord = 0.22098;
saFuse = 1;
saNose = 0; 
lenFuse = 1.2;
saTail = 2*(0.082369 + 0.14259002); %% m^2
cTail = -1;
saTailBoom = 2*pi*(0.0762/2);
TailBoom_Length = 1;
lenNose = -1;


cd0 = getZeroLiftDrag(density, viscosity, velocity, ...
sWing, saWing,chord, saFuse, lenFuse, saNose,lenNose, saTail,cTail, ...
saTailBoom, TailBoom_Length);

saWingcd0 = getZeroLiftDrag(density, viscosity, velocity, ...
sWing, saWing,chord, 0, lenFuse, 0,lenNose, 0,cTail, ...
0, TailBoom_Length)

saFusecd0 = getZeroLiftDrag(density, viscosity, velocity, ...
sWing, 0,chord, saFuse, lenFuse, 0,lenNose, 0,cTail, ...
0, TailBoom_Length)

saNosecd0 = getZeroLiftDrag(density, viscosity, velocity, ...
sWing, 0,chord, 0, lenFuse, saNose,lenNose, 0,cTail, ...
0, TailBoom_Length)

saTailcd0 = getZeroLiftDrag(density, viscosity, velocity, ...
sWing, 0,chord, 0, lenFuse, 0,lenNose, saTail,cTail, ...
0, TailBoom_Length)

saTailboomcd0 = getZeroLiftDrag(density, viscosity, velocity, ...
sWing, 0,chord, 0, lenFuse, 0,lenNose, 0,cTail, ...
saTailBoom, TailBoom_Length)